#!/bin/bash

set -e

branch=$1

if [ -z "$branch" ]; then
    echo "Usage: $0 [branch]"
    exit 1
fi

git clone -b $branch git://github.com/lirios/fluid
cd fluid
mkdir -p build
cd build
cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DFLUID_WITH_DOCUMENTATION:BOOL=OFF
make -j
make install
cd ../..
