#!/bin/bash

set -e

branch=$1

if [ -z "$branch" ]; then
    echo "Usage: $0 [branch]"
    exit 1
fi

curdir=$(dirname `readlink -f $0`)

mkdir -p /tmp/build-deps
pushd /tmp/build-deps
git clone git://github.com/liri-infra/ci-scripts
for repo in cmake-shared qtaccountsservice qtgsettings qtudev fluid libliri eglfs wayland; do
    if [ "$repo" == "fluid" ]; then
        args="-DFLUID_WITH_DOCUMENTATION:BOOL=OFF"
    else
        args=""
    fi
    ./ci-scripts/build-liri $repo $branch $args
done
popd
