name: COPR

on:
  push:
    branches:
      - develop

jobs:
  copr:
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    runs-on: ubuntu-latest
    steps:
      - run: curl -X POST ${{ secrets.COPR_WEBHOOK_URL }}
